openapi: 3.0.0
info:
  title: GS-KO Platform API
  version: "1.0"
servers:
  - url: https://api.example.com
paths:
  /ko_runs/{runId}:
    get:
      summary: Retrieve flux results for a knockout run
      parameters:
        - in: path
          name: runId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of flux results for the given run
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FluxList'
components:
  schemas:
    FluxList:
      type: array
      items:
        type: object
        properties:
          reaction_id:
            type: string
          flux_value:
            type: number
